spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_network
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: ${MAIL_SMTP_PORT}
    username: kae
    password: kae
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 3000

application:
  security:
    jwt:
      secret-key: search-for-secret-key-generators-online
      expiration: 86400000
    cors:
      allowed-origins:
        - "http://localhost:3000" # Hoppscotch Local UI
        - "http://localhost:4200" # Frontend Angular/React app
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account

server:
  port: 8088